/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/capitals`; params?: Router.UnknownInputParams; } | { pathname: `/continents`; params?: Router.UnknownInputParams; } | { pathname: `/currencies`; params?: Router.UnknownInputParams; } | { pathname: `/flags-sprint`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/landmarks`; params?: Router.UnknownInputParams; } | { pathname: `/languages`; params?: Router.UnknownInputParams; } | { pathname: `/us-capitals`; params?: Router.UnknownInputParams; } | { pathname: `/us-states`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/capitals`; params?: Router.UnknownOutputParams; } | { pathname: `/continents`; params?: Router.UnknownOutputParams; } | { pathname: `/currencies`; params?: Router.UnknownOutputParams; } | { pathname: `/flags-sprint`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/landmarks`; params?: Router.UnknownOutputParams; } | { pathname: `/languages`; params?: Router.UnknownOutputParams; } | { pathname: `/us-capitals`; params?: Router.UnknownOutputParams; } | { pathname: `/us-states`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/capitals${`?${string}` | `#${string}` | ''}` | `/continents${`?${string}` | `#${string}` | ''}` | `/currencies${`?${string}` | `#${string}` | ''}` | `/flags-sprint${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/landmarks${`?${string}` | `#${string}` | ''}` | `/languages${`?${string}` | `#${string}` | ''}` | `/us-capitals${`?${string}` | `#${string}` | ''}` | `/us-states${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/capitals`; params?: Router.UnknownInputParams; } | { pathname: `/continents`; params?: Router.UnknownInputParams; } | { pathname: `/currencies`; params?: Router.UnknownInputParams; } | { pathname: `/flags-sprint`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/landmarks`; params?: Router.UnknownInputParams; } | { pathname: `/languages`; params?: Router.UnknownInputParams; } | { pathname: `/us-capitals`; params?: Router.UnknownInputParams; } | { pathname: `/us-states`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
